import { Injectable, signal } from '@angular/core';

import {
  MovimientoInventario,
  StockProductoSede,
} from '../models/inventario.model';

@Injectable({ providedIn: 'root' })
export class InventarioStore {
  readonly stocks = signal<StockProductoSede[]>(SEED_STOCKS.map((item) => ({ ...item })));
  readonly movimientos = signal<MovimientoInventario[]>(SEED_MOVIMIENTOS.map((item) => ({ ...item })));

  /**
   * Aplica mutaciones de stock/kardex y restaura el snapshot si algo falla.
   * Lo usan aperturas y ajustes compuestos para no dejar el libro a medias.
   */
  transaccionar<T>(work: () => T): T {
    const stocks = this.stocks().map((item) => ({ ...item }));
    const movimientos = this.movimientos().map((item) => ({ ...item }));
    try {
      return work();
    } catch (error) {
      this.stocks.set(stocks);
      this.movimientos.set(movimientos);
      throw error;
    }
  }
}

const SEED_STOCKS: StockProductoSede[] = [
  stock('stk-001', 'sede-mira', 'prd-001', 4, 1),
  stock('stk-002', 'sede-mira', 'prd-002', 2, 1),
  stock('stk-003', 'sede-mira', 'prd-003', 8, 2),
  stock('stk-004', 'sede-mira', 'prd-004', 1, 1),
  stock('stk-005', 'sede-mira', 'prd-005', 3, 1),
  stock('stk-006', 'sede-mira', 'prd-007', 9, 1),
  stock('stk-007', 'sede-mira', 'prd-008', 2, 0),
  stock('stk-008', 'sede-surco', 'prd-001', 2, 0),
  stock('stk-009', 'sede-surco', 'prd-003', 3, 0),
  stock('stk-010', 'sede-surco', 'prd-005', 3, 0),
  stock('stk-011', 'sede-surco', 'prd-006', 0, 0),
  stock('stk-012', 'sede-surco', 'prd-007', 8, 0),
  stock('stk-013', 'sede-surco', 'prd-008', 1, 0),
];

const SEED_MOVIMIENTOS: MovimientoInventario[] = [
  mov({
    id: 'mov-001',
    sedeId: 'sede-surco',
    productoId: 'prd-005',
    tipoMovimiento: 'INGRESO_COMPRA',
    cantidad: 6,
    stockAnterior: 0,
    stockPosterior: 6,
    reservadoAnterior: 0,
    reservadoPosterior: 0,
    referenciaTipo: 'COMPRA',
    referenciaId: 'cmp-014',
    motivo: 'Compra ETB Prismatic Evolutions',
    usuario: 'Almacén',
    fechaCreacion: '2026-08-10T10:15:00-05:00',
  }),
  mov({
    id: 'mov-002',
    sedeId: 'sede-mira',
    productoId: 'prd-005',
    tipoMovimiento: 'APERTURA_SALIDA_SELLADO',
    cantidad: 1,
    stockAnterior: 4,
    stockPosterior: 3,
    reservadoAnterior: 0,
    reservadoPosterior: 0,
    referenciaTipo: 'APERTURA_TCG',
    referenciaId: 'apt-003',
    motivo: 'Apertura ETB en tienda',
    usuario: 'Yhort',
    fechaCreacion: '2026-08-12T16:40:00-05:00',
  }),
  mov({
    id: 'mov-003',
    sedeId: 'sede-mira',
    productoId: 'prd-001',
    tipoMovimiento: 'APERTURA_INGRESO_CARTA',
    cantidad: 1,
    stockAnterior: 3,
    stockPosterior: 4,
    reservadoAnterior: 0,
    reservadoPosterior: 0,
    referenciaTipo: 'APERTURA_TCG',
    referenciaId: 'apt-003',
    motivo: 'Charizard ex NM foil del ETB',
    usuario: 'Yhort',
    fechaCreacion: '2026-08-12T16:41:00-05:00',
  }),
  mov({
    id: 'mov-004',
    sedeId: 'sede-mira',
    productoId: 'prd-007',
    tipoMovimiento: 'ARMADO_COMPUESTO',
    cantidad: 1,
    stockAnterior: 11,
    stockPosterior: 10,
    reservadoAnterior: 0,
    reservadoPosterior: 0,
    referenciaTipo: 'COMPUESTO',
    referenciaId: 'kit-001',
    motivo: 'Salida de fundas para kit inicio',
    usuario: 'Tienda',
    fechaCreacion: '2026-08-14T11:05:00-05:00',
  }),
  mov({
    id: 'mov-005',
    sedeId: 'sede-mira',
    productoId: 'prd-008',
    tipoMovimiento: 'ARMADO_COMPUESTO',
    cantidad: 1,
    stockAnterior: 1,
    stockPosterior: 2,
    reservadoAnterior: 0,
    reservadoPosterior: 0,
    referenciaTipo: 'COMPUESTO',
    referenciaId: 'kit-001',
    motivo: 'Ingreso kit inicio Pokémon',
    usuario: 'Tienda',
    fechaCreacion: '2026-08-14T11:06:00-05:00',
  }),
  mov({
    id: 'mov-006',
    sedeId: 'sede-surco',
    productoId: 'prd-008',
    tipoMovimiento: 'DESARME_COMPUESTO',
    cantidad: 1,
    stockAnterior: 2,
    stockPosterior: 1,
    reservadoAnterior: 0,
    reservadoPosterior: 0,
    referenciaTipo: 'COMPUESTO',
    referenciaId: 'kit-002',
    motivo: 'Desarme de kit para venta suelta',
    usuario: 'Almacén',
    fechaCreacion: '2026-08-16T09:20:00-05:00',
  }),
  mov({
    id: 'mov-007',
    sedeId: 'sede-mira',
    productoId: 'prd-001',
    tipoMovimiento: 'PUJA_GANADORA_RESERVA',
    cantidad: 1,
    stockAnterior: 4,
    stockPosterior: 4,
    reservadoAnterior: 0,
    reservadoPosterior: 1,
    referenciaTipo: 'SUBASTA_TCG',
    referenciaId: 'sub-018',
    motivo: 'Puja ganadora Facebook · Charizard ex',
    usuario: 'Subastas',
    fechaCreacion: '2026-08-18T21:12:00-05:00',
  }),
  mov({
    id: 'mov-008',
    sedeId: 'sede-mira',
    productoId: 'prd-003',
    tipoMovimiento: 'RESERVA',
    cantidad: 2,
    stockAnterior: 8,
    stockPosterior: 8,
    reservadoAnterior: 0,
    reservadoPosterior: 2,
    referenciaTipo: 'PEDIDO_DIGITAL',
    referenciaId: 'ped-044',
    motivo: 'Pedido WhatsApp Lightning Bolt x2',
    usuario: 'Pedidos',
    fechaCreacion: '2026-08-19T13:30:00-05:00',
  }),
  mov({
    id: 'mov-009',
    sedeId: 'sede-mira',
    productoId: 'prd-004',
    tipoMovimiento: 'AJUSTE',
    cantidad: 1,
    stockAnterior: 2,
    stockPosterior: 1,
    reservadoAnterior: 1,
    reservadoPosterior: 1,
    referenciaTipo: 'AJUSTE_MANUAL',
    referenciaId: null,
    motivo: 'Carta dañada en vitrina · baja de inventario',
    usuario: 'Yhort',
    fechaCreacion: '2026-08-20T18:05:00-05:00',
  }),
  mov({
    id: 'mov-010',
    sedeId: 'sede-mira',
    productoId: 'prd-007',
    tipoMovimiento: 'VENTA',
    cantidad: 1,
    stockAnterior: 11,
    stockPosterior: 10,
    reservadoAnterior: 0,
    reservadoPosterior: 0,
    referenciaTipo: 'VENTA',
    referenciaId: 'vta-220',
    motivo: 'Venta mostrador fundas',
    usuario: 'Caja',
    fechaCreacion: '2026-08-21T12:48:00-05:00',
  }),
  mov({
    id: 'mov-011',
    sedeId: 'sede-mira',
    productoId: 'prd-005',
    tipoMovimiento: 'RESERVA',
    cantidad: 1,
    stockAnterior: 3,
    stockPosterior: 3,
    reservadoAnterior: 0,
    reservadoPosterior: 1,
    referenciaTipo: 'PEDIDO_DIGITAL',
    referenciaId: 'ped-050',
    motivo: 'Reserva pedido ped-050 · Elite Trainer Box — Prismatic Evolutions',
    usuario: 'Pedidos',
    fechaCreacion: '2026-08-20T09:15:00-05:00',
  }),
  mov({
    id: 'mov-012',
    sedeId: 'sede-mira',
    productoId: 'prd-002',
    tipoMovimiento: 'RESERVA',
    cantidad: 1,
    stockAnterior: 2,
    stockPosterior: 2,
    reservadoAnterior: 0,
    reservadoPosterior: 1,
    referenciaTipo: 'PEDIDO_DIGITAL',
    referenciaId: 'ped-051',
    motivo: 'Reserva pedido ped-051 · Pikachu — Paldea Evolved 070/193',
    usuario: 'Pedidos',
    fechaCreacion: '2026-08-20T16:40:00-05:00',
  }),
  mov({
    id: 'mov-013',
    sedeId: 'sede-mira',
    productoId: 'prd-007',
    tipoMovimiento: 'VENTA',
    cantidad: 1,
    stockAnterior: 10,
    stockPosterior: 9,
    reservadoAnterior: 1,
    reservadoPosterior: 0,
    referenciaTipo: 'VENTA',
    referenciaId: 'vta-301',
    motivo: 'Venta desde pedido ped-060 · Fundas Dragon Shield Matte Jet 100',
    usuario: 'Pedidos',
    fechaCreacion: '2026-08-19T15:40:00-05:00',
  }),
  mov({
    id: 'mov-014',
    sedeId: 'sede-mira',
    productoId: 'prd-007',
    tipoMovimiento: 'RESERVA',
    cantidad: 1,
    stockAnterior: 9,
    stockPosterior: 9,
    reservadoAnterior: 0,
    reservadoPosterior: 1,
    referenciaTipo: 'PEDIDO_DIGITAL',
    referenciaId: 'ped-052',
    motivo: 'Reserva pedido ped-052 · Fundas Dragon Shield Matte Jet 100',
    usuario: 'Pedidos',
    fechaCreacion: '2026-08-21T12:10:00-05:00',
  }),
];

function stock(
  id: string,
  sedeId: string,
  productoId: string,
  cantidadDisponible: number,
  cantidadReservada: number,
): StockProductoSede {
  return { id, sedeId, productoId, cantidadDisponible, cantidadReservada };
}

function mov(item: MovimientoInventario): MovimientoInventario {
  return item;
}
