// <auto-generated />
using System;
using CapitalPos.Tcg.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CapitalPos.Tcg.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260828175256_AddUsuarioPasswordHash")]
    partial class AddUsuarioPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("ruc");

                    b.HasKey("Id");

                    b.HasIndex("Ruc")
                        .IsUnique()
                        .HasDatabaseName("ux_empresas_ruc");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("referencia_id");

                    b.Property<string>("ReferenciaTipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("referencia_tipo");

                    b.Property<decimal>("ReservadoAnterior")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("reservado_anterior");

                    b.Property<decimal>("ReservadoPosterior")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("reservado_posterior");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sede_id");

                    b.Property<decimal>("StockAnterior")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("stock_anterior");

                    b.Property<decimal>("StockPosterior")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("stock_posterior");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_movimiento");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EmpresaId", "ProductoId");

                    b.HasIndex("EmpresaId", "ReferenciaTipo", "ReferenciaId")
                        .HasDatabaseName("ix_movimientos_inventario_empresa_referencia");

                    b.HasIndex("EmpresaId", "SedeId", "ProductoId", "FechaCreacion")
                        .HasDatabaseName("ix_movimientos_inventario_empresa_sede_producto_fecha");

                    b.ToTable("movimientos_inventario", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("CodigoSku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("codigo_sku");

                    b.Property<decimal?>("Costo")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("costo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<Guid?>("MarcaId")
                        .HasColumnType("uuid")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_venta");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tipo_producto");

                    b.HasKey("Id");

                    b.HasAlternateKey("EmpresaId", "Id")
                        .HasName("ak_productos_empresa_id");

                    b.HasIndex("EmpresaId", "CodigoSku")
                        .IsUnique()
                        .HasDatabaseName("ux_productos_empresa_id_codigo_sku");

                    b.ToTable("productos", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<string>("Departamento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("departamento");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("Distrito")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("distrito");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<bool>("EsAlmacenPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_almacen_principal");

                    b.Property<bool>("EsPuntoLlegadaGre")
                        .HasColumnType("boolean")
                        .HasColumnName("es_punto_llegada_gre");

                    b.Property<bool>("EsPuntoPartidaGre")
                        .HasColumnType("boolean")
                        .HasColumnName("es_punto_partida_gre");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("Provincia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provincia");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tipo");

                    b.Property<string>("Ubigeo")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("ubigeo");

                    b.HasKey("Id");

                    b.HasAlternateKey("EmpresaId", "Id")
                        .HasName("ak_sedes_empresa_id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .HasDatabaseName("ix_sedes_empresa_id_nombre");

                    b.ToTable("sedes", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.StockProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad_disponible");

                    b.Property<decimal>("CantidadLibre")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad_libre")
                        .HasComputedColumnSql("cantidad_disponible - cantidad_reservada", true);

                    b.Property<decimal>("CantidadReservada")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("cantidad_reservada");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid")
                        .HasColumnName("sede_id");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId");

                    b.HasIndex("EmpresaId", "SedeId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ux_stocks_productos_empresa_sede_producto");

                    b.ToTable("stocks_productos", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_empresa_id_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.ProductoCarta", b =>
                {
                    b.HasBaseType("CapitalPos.Tcg.Api.Domain.Entities.Producto");

                    b.Property<string>("Artista")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("artista");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("condicion");

                    b.Property<bool>("EsFoil")
                        .HasColumnType("boolean")
                        .HasColumnName("es_foil");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("idioma");

                    b.Property<string>("Juego")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("juego");

                    b.Property<string>("NumeroCarta")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("numero_carta");

                    b.Property<string>("Rareza")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("rareza");

                    b.Property<string>("SetCodigo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("set_codigo");

                    b.Property<string>("SetNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("set_nombre");

                    b.ToTable("producto_cartas", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.ProductoSellado", b =>
                {
                    b.HasBaseType("CapitalPos.Tcg.Api.Domain.Entities.Producto");

                    b.Property<int>("CartasEsperadas")
                        .HasColumnType("integer")
                        .HasColumnName("cartas_esperadas");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("edicion");

                    b.Property<string>("Juego")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("juego");

                    b.Property<bool>("PermiteApertura")
                        .HasColumnType("boolean")
                        .HasColumnName("permite_apertura");

                    b.Property<string>("TipoSellado")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tipo_sellado");

                    b.ToTable("producto_sellados", (string)null);
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.MovimientoInventario", b =>
                {
                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("EmpresaId", "ProductoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Sede", "Sede")
                        .WithMany("Movimientos")
                        .HasForeignKey("EmpresaId", "SedeId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Producto");

                    b.Navigation("Sede");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Producto", b =>
                {
                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Productos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Sede", b =>
                {
                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Sedes")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.StockProducto", b =>
                {
                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Producto", "Producto")
                        .WithMany("Stocks")
                        .HasForeignKey("EmpresaId", "ProductoId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Sede", "Sede")
                        .WithMany("Stocks")
                        .HasForeignKey("EmpresaId", "SedeId")
                        .HasPrincipalKey("EmpresaId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Producto");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.ProductoCarta", b =>
                {
                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("CapitalPos.Tcg.Api.Domain.Entities.ProductoCarta", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.ProductoSellado", b =>
                {
                    b.HasOne("CapitalPos.Tcg.Api.Domain.Entities.Producto", null)
                        .WithOne()
                        .HasForeignKey("CapitalPos.Tcg.Api.Domain.Entities.ProductoSellado", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Sedes");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Sede", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("CapitalPos.Tcg.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
